name: uklmobileapps
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.9.2
  flutter_bloc: ^9.1.1
  equatable: ^2.0.8
  shared_preferences: ^2.5.5
  carousel_slider: ^5.1.2
  flutter_dotenv: ^6.0.1
  amicons: ^1.0.1
  fl_chart: ^1.2.0
  image_picker: ^1.2.2
  permission_handler: ^12.0.2
  image_gallery_saver_plus: ^4.0.1
  google_fonts: ^8.1.0
  flutter_svg: ^2.3.0
  syncfusion_flutter_charts: ^33.2.8
  intl: ^0.20.2
  dotted_border: ^3.1.0
  dotted_line: ^3.3.0
  flutter_dotted: ^0.0.5
  # 💡 Dihapus dari sini karena ini adalah tools development

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  # 💡 Dipindahkan ke sini agar aplikasi Anda lebih ringan saat di-build production
  flutter_launcher_icons: ^0.14.4

# 🔥 TAMBAHKAN KONFIGURASI INI DI BAGIAN PALING BAWAH (SEJAJAR DENGAN DEPAN/UTAMA)
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/apk.png" # Menggunakan asset SVG yang ada di daftar Anda
  min_sdk_android: 21 # Menyesuaikan batas minimum SDK Android Anda

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/ilustrasi1.svg
    - assets/ilustrasi2.svg
    - assets/ilustrasi3.svg
    - assets/buttonscirt.svg
    - assets/warning.svg
    - assets/card_register-login.svg
    - assets/register.svg
    - assets/login.svg
    - assets/Close.svg
    - assets/loginBackground.svg
    - assets/profilCus.svg
    - assets/tagihanTerbit.svg
    - assets/WellnessCard.svg
    - assets/logo_bils.svg
    - assets/done.svg
    - assets/blue.svg
    - assets/tunggak.svg
    - assets/go.svg
    - assets/tips.svg
    - assets/home.svg
    - assets/trans.svg
    - assets/Profile.svg
    - assets/home_fill.svg
    - assets/trans_fill.svg
    - assets/Profile_fill.svg
    - assets/Succes_page.svg
    - assets/akun.svg
    - assets/profilback.svg
    - assets/customor.svg
    - assets/service.svg
    - assets/customor_fill.svg
    - assets/service_fill.svg
    - assets/admin.svg
    - assets/icon.svg
    - assets/delate.svg
    - assets/edit.svg
    - assets/Search.svg
    - assets/icondone.svg
    - assets/profiladmin.svg
    - assets/Intersect.svg
    - assets/apk.png